osx_image: xcode7.2
language: objective-c
script:
  - pushd FeedDemo-ObjectiveC
  - pod install
  - ./scripts/build.sh
  - popd
  - pushd FeedDemo-Swift
  - pod install
  - ./scripts/build.sh
  - popd
notifications:
  slack:
    rooms:
      - applicaster:G6WSNVws3sCXTXBsXbkNdwtK#bot-ci-modular-sdk
