osx_image: xcode7.2
language: objective-c
git:
  submodules: false
script:
  - pushd FeedDemo-ObjectiveC
  - pod install
  - ./scripts/build.sh | xcpretty
  - popd
  - pushd FeedDemo-Swift
  - pod install
  - ./scripts/build.sh | xcpretty
  - popd
notifications:
  slack:
    rooms:
      - applicaster:G6WSNVws3sCXTXBsXbkNdwtK#bot-ci-modular-sdk
