platform :ios, "8.0"
use_frameworks!

source 'git@github.com:applicaster/CocoaPods.git'
source 'git@github.com:applicaster/CocoaPods-Private.git'
source 'git@github.com:CocoaPods/Specs.git'

target 'FeedDemo-ObjectiveC' do
    pod 'APFeed', '~> 3.5.5'
end
