platform :ios, "8.0"
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/applicaster/CocoaPods.git'

target 'FeedDemo-Swift' do
    pod 'APFeed', '~> 3.5.2'
end
