platform :ios, "8.0"
use_frameworks!

source 'git@github.com:applicaster/CocoaPods.git'
source 'git@github.com:applicaster/CocoaPods-Private.git'
source 'git@github.com:CocoaPods/Specs.git'

pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    def installer.verify_no_static_framework_transitive_dependencies; end
end

target 'FeedDemo-Swift' do
    pod 'APFeed', '3.6.0'
    pod 'ZappAnalyticsPlugins/GoogleAnalytics','~> 1.7.0'
    pod 'ZappAnalyticsPlugins/Flurry','~> 1.7.0'
    pod 'ZappAnalyticsPlugins','~> 1.7.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
